### PR TITLE
Accessibility: Setting headings' visual styles in an accessible way 

### LINKED ISSUE #319: Accessibility: heading elements should be in a sequentially-descending order
## Problem

The Chooser currently uses the `<h1>`-`<h6>` heading levels according to the design. Headings are used for creating the outline for a page, which is important for accessibility purposes. Skipping heading levels makes the outline, or website's table of contents, incorrect. This also lowers our Lighthouse Accessibility score:
image

## Description

Fortunately, CC's design system provides a way to use the headings' visual styles in an accessible way:

To create a second-level heading that visually looks like `<h5>`, we can use `<h2 class="title is-5">`. 

So, this is the list of changes that need to be introduced:

- Main heading ('License Chooser') should be `<h1>` that looks like `h2`
- Section headings (`h3`) should be `<h2>` with the style of `h3`
- Step header headings (`h5`) should be `<h2>` with the style of `h5`

## Implementation

- [ ] I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by neeraj-2**
## Fixes

Fixes #319  by @obulat

## Description

It sets the headings' visual styles in an accessible way and thus enhances accessibility.

## Screenshots

image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by neeraj-2** [comment]
@obulat I think there is some problem with testing. I ran the "npm run test" command and got some errors even initially without making any changes.
image

image

**Comment by Cronus1007** [comment]
@obulat The tests for #272 which is arising this error.

**Review by obulat — CHANGES_REQUESTED** [review]
Thank you for your great work, @neeraj-2! This PR can be merge after a couple of minor changes are added.

**Comment by obulat** [comment]
> @obulat I think there is some problem with testing. I ran the "npm run test" command and got some errors even initially without making any changes.
> image
> 
Actually, this was my mistake: this logic should be tested in integration tests, not the unit tests as it is now. Can you please delete the failing test?

**Review by zackkrida — APPROVED** [review]
Great work! Thank you.

**Comment by neeraj-2** [comment]
> Great work! Thank you.

Thanks, @zackkrida, and @obulat

**Pull request merged**
