### PR TITLE
Header component uint test and e2e test

### LINKED ISSUE #124: Add unit and e2e tests for the App component
Unit and e2e tests need to be written for the App component. Unit tests are done with [Jest](https://jestjs.io/), and e2e tests are done with [nightwatch](https://nightwatchjs.org/).

Please remember to test the following things:
- That individual parts of the component are present when appropriate. (unit and e2e)
- That any computed props and methods work properly, if there are any. (unit)
- Any common interactions between the user and component, if there are any. (e2e)
- Any other functionality unique to the component being tested!

### Additional Context
- [./src/App.vue](https://github.com/creativecommons/cc-chooser/blob/master/src/App.vue)
- [This repo's testing README](https://github.com/creativecommons/cc-chooser/blob/master/tests/README.md)
- [Vue's guide on unit testing](https://vuejs.org/v2/guide/unit-testing.html)
- [Vue's guide on unit testing with VueX](https://vue-test-utils.vuejs.org/guides/using-with-vuex.html)

### PR DESCRIPTION
**Pull request by achilep**
Fixes #124 

## Description

Add unit and e2e tests for the App component
## Other information

i have created the  test for Header component only as prototype.  i wish to know if you can given some feedback before i start write for the app component   thank you.

### CODE REVIEW

**Comment by achilep** [comment]
thank you sir

**Comment by achilep** [comment]
i will change it

**Comment by obulat** [comment]
Header component will eventually be replaced by a common header component from Creative Commons Vocabulary library of components, so it is not necessary to test it. This is why I am closing this PR. Feel free to open a new PR for tests of the App component (#124).

**Comment by achilep** [comment]
Ok ,no problem

**Pull request closed without merging**
