### PR TITLE
License consideration

### LINKED ISSUE #288: "This work marked"
## Description
When a work is marked under CC0 it should say: "this work IS marked under CC0". The verb is missing

## Reproduction

1. Generate a CC0 license waive2
2. It will say "this work marked under" with no "is".

## Expectation
It should make grammatical sense.

## Resolution
- [ ] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by neeraj-2**
## Fixes

Fixes #288  by @Aspie96 

## Description

It Corrects a typo when a user generates a CC0 license waive2

## Screenshots

image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
This is great! Could you also please run `npm run build` and commit it, too? This way it will be deployed to the beta site.

**Comment by neeraj-2** [comment]
> This is great! Could you also please run `npm run build` and commit it, too? This way it will be deployed to the beta site.

Sure @obulat

**Comment by neeraj-2** [comment]
> > This is great! Could you also please run `npm run build` and commit it, too? This way it will be deployed to the beta site.
> 
> Sure @obulat



> This is great! Could you also please run `npm run build` and commit it, too? This way it will be deployed to the beta site.

@obulat, I ran the build command and some of the files changed. Should I just make a commit. I am not sure how it works( Deployment part specifically)

**Comment by obulat** [comment]
> > > This is great! Could you also please run `npm run build` and commit it, too? This way it will be deployed to the beta site.
> > 
> > Sure @obulat
> 
> 
> 
> > This is great! Could you also please run `npm run build` and commit it, too? This way it will be deployed to the beta site.
> 
> @obulat, I ran the build command and some of the files changed. Should I just make a commit. I am not sure how it works( Deployment part specifically) 

Yes, add all the changed files, commit and push them. Anything that's inside the docs folder is automatically deployed.

**Review by obulat — CHANGES_REQUESTED** [review]
Thank you, @neeraj-2 , the only thing left is to add file called `CNAME` and commit and push it, too.

**Comment by neeraj-2** [comment]
> Thank you, @neeraj-2 , the only thing left is to add file called `CNAME` and commit and push it, too.

I think it is already added. Am I wrong?

**Review by obulat — APPROVED** [review]

**Comment by obulat** [comment]
Oh, it was my mistake, it seems that CMAKE is there. Thank you for your contributions, @neeraj-2 !

**Comment by neeraj-2** [comment]
> Oh, it was my mistake, it seems that CMAKE is there. Thank you for your contributions, @neeraj-2 !

Thanks, @obulat and @Aspie96

**Pull request merged**
