### PR TITLE
Added unit and e2e tests for HelpSection.vue component

### LINKED ISSUE #116: Add unit and e2e tests for the HelpSection component
Unit and e2e tests need to be written for the HelpSection component. Unit tests are done with [Jest](https://jestjs.io/), and e2e tests are done with [nightwatch](https://nightwatchjs.org/).

Please remember to test the following things:
- That individual parts of the component are present when appropriate. (unit and e2e)
- That any computed props and methods work properly, if there are any. (unit)
- Any common interactions between the user and component, if there are any. (e2e)
- Any other functionality that is unique to the component being tested!

### Additional Context
- [./src/components/HelpSection.vue](https://github.com/creativecommons/cc-chooser/blob/master/src/components/HelpSection.vue)
- [This repo's testing README](https://github.com/creativecommons/cc-chooser/blob/master/tests/README.md)
- [Vue's guide on unit testing](https://vuejs.org/v2/guide/unit-testing.html)
- [Vue's guide on unit testing with VueX](https://vue-test-utils.vuejs.org/guides/using-with-vuex.html)

### PR DESCRIPTION
**Pull request by hemanth-hk**
Fixes #116

## Description
I have added the unit and e2e tests for the HelpSection.vue component. And tested it locally

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin
```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open-source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open-source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by hemanth-hk** [comment]
I was able to mock the $ga of Vue analytics but the method using it, was not returning anything, so I had to return something, hence I returned the return of the $ga.event function

Please review and check if I have left any cases like last time

**Comment by akmadian** [comment]
@hemanth-hk We don't need to mock ga as there's no way I know of to verify that the event was received by ga without writing a bunch more code. Please remove all ga stuff and I'll have another look :)

**Comment by hemanth-hk** [comment]
When I removed the ga stuff the test coverage was not 100%

**Comment by hemanth-hk** [comment]
### This is the screenshot of the unit test before mocking $ga
before-ga-stuff

---

### This is the screenshot of the unit test after mocking $ga
after-ga-stuff

**Comment by obulat** [comment]
> When I removed the ga stuff the test coverage was not 100%

It's ok for coverage not to be 100% in this case.

**Comment by hemanth-hk** [comment]
@obulat I would have removed them if you have just left a comment but please make sure you also remove the return statement form the Helpsection.vue component which I added to check it

**Comment by obulat** [comment]
Sorry about that, @hemanth-hk . I wanted to add some changes to quickly clean up errors in the repo to make it easier for other contributors to work on it, that is why I added some more changes here. Unfortunately, I didn't notice the return statement. Could you please create a PR removing it?

**Comment by hemanth-hk** [comment]
I added them in #154, That would be fine right?

**Comment by obulat** [comment]
Sure, you acted before I could reply. Thank you again, the repo is linted and test run well now!

**Pull request merged**
