### PR TITLE
Add "license appropriateness" step to chooser flow

### LINKED ISSUE #314: Add step to determine appropriateness of CC licenses
## Description

Users who aren't familiar with Creative Commons licenses might not know if the licenses are actually appropriate for their work and use case. We would like to add a step to the chooser that lets the user confirm a CC license is the right fit.

This issue will be updated with the exact copy, but in the meantime a **draft pull request** may be created that adds a 'generic' new second step to the chooser flow, that can be filled in with the appropriate content when ready.

### PR DESCRIPTION
**Pull request by neeraj-2**
## Fixes

Fixes #314  by @zackkrida 

## Description

It adds a new step to the stepper.

## Screenshots

ezgif com-video-to-gif(1)

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the *default* branch of the repository (`main` or `master`).
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
@obulat Could you help review this PR this week? For your information, the step might not have radio buttons, which complicates things a bit.

**Comment by neeraj-2** [comment]
@zackkrida what should be the heading of the new step?

**Comment by zackkrida** [comment]
Hi @neeraj-2, I reviewed your code and it looks really good! I have some new details for you and the copy for the step:

- This step is basically a copy of the [CopyrightWaiverStep.vue](https://github.com/creativecommons/chooser/blob/4a26904891e10a7b897ce0a858a7f304fc3af7fb/src/components/CopyrightWaiverStep.vue#L0-L1) step, and will have three checkboxes added. Here's all the copy you'll need:

### Heading

Confirm that CC licensing is appropriate 

### Checkboxes
- I own or have authority to license the work. 
- I have read and understand the terms of the license. 
- I understand that CC licensing is not revocable. 

Awesome work so far; thank you.

**Comment by neeraj-2** [comment]
> Hi @neeraj-2, I reviewed your code and it looks really good! I have some new details for you and the copy for the step:
> 
> * This step is basically a copy of the [CopyrightWaiverStep.vue](https://github.com/creativecommons/chooser/blob/4a26904891e10a7b897ce0a858a7f304fc3af7fb/src/components/CopyrightWaiverStep.vue#L0-L1) step, and will have three checkboxes added. Here's all the copy you'll need:
> 
> ### Heading
> Confirm that CC licensing is appropriate
> 
> ### Checkboxes
> * I own or have authority to license the work.
> * I have read and understand the terms of the license.
> * I understand that CC licensing is not revocable.
> 
> Awesome work so far; thank you.

Thanks, @zackkrida, will continue working on this issue as per the details you mentioned here.

**Comment by neeraj-2** [comment]
Hey @zackkrida, just a problem here in the new step also that is also mentioned in issue #323. I Will start working on it. But again want your suggestions for the same. I already mentioned the approaches that I thought of, in issue #323.

**Review by zackkrida — APPROVED** [review]
~oops, i commented on the incorrect pr.~

**Comment by zackkrida** [comment]
Hey @neeraj-2 this became a little time sensitive since I'm leaving CC next week, so I went in and fixed the checkbox state issue. Really great work here, thanks for getting the hard parts done 👏

**Comment by neeraj-2** [comment]
> Hey @neeraj-2 this became a little time sensitive since I'm leaving CC next week, so I went in and fixed the checkbox state issue. Really great work here, thanks for getting the hard parts done 👏

Thanks, @zackkrida

**Pull request merged**
