### PR TITLE
Corrected Dublin Core Terms namespace

### PR DESCRIPTION
**Pull request by Bobulous**
Modified namespace prefix from "dc" to "dct" within the span element for the title, to match the xmlns:dct declaration for the Dublin Core Terms namespace.

## Description

Unless I'm misunderstanding the intent of the code, the span element for the title is trying to refer to the Dublin Core Terms "title" property, in which case I believe it should be referring to the "dct" namespace prefix declared within one of its ancestor elements.

## Checklist
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `master` branch of the repository.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin
```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by akmadian** [comment]
I'm going to close this PR, please include these changes in #134

**Comment by akmadian** [comment]
My apologies, I didn't see your comment about editing multiple files per patch in your other PR :) The changes look good to me, i'll wait on Olga's approval on your other PR to merge this one

**Comment by Bobulous** [comment]
Yeah, I did try to get both changes into a single pull request, but couldn't find a way to do it. If someone knows the secret, let me know.

**Comment by obulat** [comment]
@Bobulous , thank you for your PR! To be honest, I am not very familiar with the markup. I used the markup from [this document](https://www.w3.org/Submission/ccREL/) to write the metadata with dc: for title, but a [more detailed guide on ccREL](https://labs.creativecommons.org/2011/ccrel-guide/) does use dct: for title. I am merging the PRs, thank you for your contribution!

**Pull request merged**
