### PR TITLE
add more context to the Creator name

### LINKED ISSUE #326: Feature: Add more context to Creator Name
## Description

Add the following text near the `Creator Name` field: 

> In addition to the creator of the work, include here any others who should receive attribution. For example, if you created a work on behalf of your employer who owns copyright in the work, you may want to include your employer’s name as one of the attribution parties.

## Alternatives

We should figure out how to best add this copy without cluttering the UI too much. Should it be in an info ℹ️ popup/tooltip, a modal, or right inline with the copy? I'm open to suggestions from whoever implements the issue.

### PR DESCRIPTION
**Pull request by Cronus1007**
## Fixes
Fixes #326  by @zackkrida 

## Description

- Added Feature to add more context to the Creator Name. 
- Added Modals while clicking upon the Info Icon
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Cronus1007** [comment]
@panchovm Have a look at the below ss and plzzz update me where to put the required info Button.
Screenshot from 2021-02-26 16-04-12

**Comment by panchovm** [comment]
Thanks for working on this, my only suggestion is to move the icon on the right side of "Creator of Work" sentence.

**Review by zackkrida — CHANGES_REQUESTED** [review]
This is close to ready, but a few issues:

- [ ] Closing the modal doesn't actually work
- [ ] Reduce the info icon margin-left to `0.3rem` please

Thanks for doing this @Cronus1007 !

**Comment by Cronus1007** [comment]
@zackkrida Can you plzz provide me any hint for closing the modal. I have also tried `this.$emit('close)` but still it is not working.Any ideas reagarding the implementation.

**Comment by obulat** [comment]
> @zackkrida @obulat Can you plzz provide me any hint for closing the modal. I have also tried `this.$emit('close)` but still it is not working. Any ideas regarding the implementation.

You emit a close event from the AppModal, but you don't have anything to handle this event. You need to have a property on the parent component that controls modal's state. You can see how it works in `CopyrightWaiverStep`, line 85.

**Comment by obulat** [comment]
Please, also read the linked commit message best practices: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53
It is difficult to read the code history and find where someone introduced the change you are looking for when you have multiple commits with names such as 'improvements' or 'message' in the history of the project.

**Comment by Cronus1007** [comment]
> You emit a close event from the AppModal, but you don't have anything to handle this event. You need to have a property on the parent component that controls modal's state. You can see how it works in `CopyrightWaiverStep`, line 85.

@obulat Can you plzzz guide me more how  to make the required changes ?

**Review by zackkrida — APPROVED** [review]
Hi @Cronus1007 I have made some updates for you and will merge the branch now. Thank you for your work. Here's some information on the changes made (you can view the commit [here](https://github.com/creativecommons/chooser/pull/331/commits/43b460547f0860c79ed4f2cc4a784fb12a984628)):

- The reason your code wasn't working was that the `AppModal` component was _inside_ of the info button, so when the modal was clicked on to close it, it also triggered the `@click="toggleInfoModal"` on its parent. This is known as 'event bubbling' in web development. Moving the modal _outside_ of the ℹ️ `span` fixes that problem.
- `VInput` is a generic, reusable component, and shouldn't have content that is _only_ relevant to one step (in this case, the `AttributionDetailsStep`) inside of it. Instead, the modal and it's open/close logic have been moved up to the `AttributionDetailsStep.vue` file, and inserted next to the `VInput` label via a new `after-label` slot.

**Comment by Cronus1007** [comment]
@zackkrida Thanks.

**Comment by obulat** [comment]
Thank you for picking this up, @zackkrida !

**Pull request merged**
