### PR TITLE
Adjusted positioning of the 'Confused Need Help' and 'Recommended License' sections in mobile view

### LINKED ISSUE #455: [Bug] Adjust positioning of the 'Confused Need Help' and 'Recommended License' sections in mobile view
## Description
In mobile view, I think it would be better if the 'Recommended License' section is re-positioned above the 'Confused Need Help' section. In desktop view, it does not cause an issue, but in mobile view I find it meaningless to put that section above the 'Recommended License' section which users need to see to confirm the details of the chosen license.

## Reproduction

1.  Step 1 `https://chooser-beta.creativecommons.org/`
2.  Step 2 Switch to mobile view 
3. Step 3  Fill I know the License I need, then choose a license
4. See that you will always scroll past the 'Confused? Need Help' section.

## Screenshots

image

## Environment

 - Device: Mobile Devices

## Additional context

Help sections for the user are generally placed towards the bottom of the page, so this issue will address it as well.

## Resolution

- [x] I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by soustab10**
## Fixes

Fixes #455  by @soustab10 

## Description
Fixes the position of 'Confused Need Help' and 'Recommended License' sections in mobile view for better ease of the user.

## Screenshots

image
image

Device used for reference: Samsung Galaxy S20 Ultra

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by Shafiya-Heena — APPROVED** [review]
@soustab10 Thank you for the contribution.

**Comment by possumbilities** [comment]
Hi @soustab10 can you update your branch here with the latest version of main to see if the tests pass now? I merged in another PR that _should_ fix the failing tests here, but it'll need the newest commits first.

**Review by Cronus1007 — APPROVED** [review]

**Comment by soustab10** [comment]
> Hi @soustab10 can you update your branch here with the latest version of main to see if the tests pass now? I merged in another PR that _should_ fix the failing tests here, but it'll need the newest commits first.

Sure. Thank you.

**Comment by soustab10** [comment]
@possumbilities Thank you, build test has passed.

**Pull request merged**
