### PR TITLE
added new 'year-of-creation' attribution details

### LINKED ISSUE #325: Add new "year of creation" attribution detail
## Description

From Sarah in legal:

> In Attribution Details for the licenses (but not CC0), add “Year of Creation” which should manifest in the attribution text as © 2021 after the Title and before the Creator Name.

### PR DESCRIPTION
**Pull request by Cronus1007**
## Fixes
Fixes #325 by @zackkrida 

## Description
- Added the `yearOfCreation` input feild in `AD` for all the licenses except `CC0`
## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Cronus1007** [comment]
@obulat I am able to update the Attribution Details to get the year of Creation and storing the value but unable to update the front End Template.

**Review by obulat — CHANGES_REQUESTED** [review]
Year of creation should only be added to licenses, not the CC0.
So, can you please remove the Year field in the AttributionDetails for CC0, and the license code.

**Comment by Cronus1007** [comment]
@obulat I am planning to do it via adding the `shortName` attribute to the attributionDetails and then toogle will be as per the shortname. Whats your opinion upon it?

**Comment by obulat** [comment]
> @obulat I am planning to do it via adding the `shortName` attribute to the attributionDetails and then toogle will be as per the shortname. Whats your opinion upon it?
> 
Yes, using the shortName getter is a great idea.
I guess by 'toggle' you mean the v-if condition where you show the field if the shortName isn't equal to CC0.

**Comment by Cronus1007** [comment]
> I guess by 'toggle' you mean the v-if condition where you show the field if the shortName isn't equal to CC0.

Yes.

**Comment by Cronus1007** [comment]
@obulat I have resolved the test conflicts as well. Now the PR is ready for being reviewed.

**Review by zackkrida — APPROVED** [review]

**Pull request merged**
